import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { hasLocale } from "next-intl";
import {
  Amiri,
  Cormorant_Garamond,
  IBM_Plex_Sans_Arabic,
  Inter,
  Noto_Kufi_Arabic,
} from "next/font/google";
import { routing } from "@/i18n/routing";
import { Analytics } from "@vercel/analytics/next";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import "../globals.css";

// Editorial accent face (English) — italic emphasis words inside headlines
const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  // .font-accent pins weight 400 + italic, so every other combination this
  // used to declare (500/600/700, and the whole upright style) shipped a
  // font file nothing could ever render.
  weight: ["400"],
  style: ["italic"],
  variable: "--font-accent",
  display: "swap",
});

// Structural face (English) — headings AND body
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

// Structural face (Arabic) — headings and the giant wordmark
const notoKufi = Noto_Kufi_Arabic({
  subsets: ["arabic"],
  // No weight list: this pulls the VARIABLE face, one file per unicode range
  // covering the whole 100-900 axis, instead of a separate set of files per
  // static weight. font-heading legitimately uses 400-900, so the static
  // version could not be trimmed any further.
  variable: "--font-arabic",
  display: "swap",
});

// Body face (Arabic)
const plexArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  // 300 dropped — font-light appears nowhere in the codebase.
  weight: ["400", "500", "700"],
  variable: "--font-arabic-body",
  display: "swap",
});

// Editorial accent face (Arabic) — the Amiri answer to Cormorant's italics
const amiri = Amiri({
  subsets: ["arabic", "latin"],
  // Arabic .font-accent pins weight 400, so 700 was unreachable.
  weight: ["400"],
  variable: "--font-arabic-accent",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    // Child pages supply just their page name; this template appends the site name.
    template: "%s — DarSaif",
    default: "DarSaif Architecture",
  },
  description: "Architecture office based in Buraydah, Qassim, Saudi Arabia.",
  openGraph: {
    siteName: "DarSaif Architecture",
    type: "website",
    // Default og:image is generated by opengraph-image.tsx (next/og convention).
    // Per-project pages override this with their Sanity cover image.
  },
  twitter: {
    card: "summary_large_image",
  },
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  const siteUrl =
    process.env.NEXT_PUBLIC_SITE_URL ?? "https://darsaif.com";

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    name: "DarSaif Architecture",
    description:
      "Architecture office based in Buraydah, Qassim, Saudi Arabia.",
    url: siteUrl,
    address: {
      "@type": "PostalAddress",
      addressLocality: "Buraydah",
      addressRegion: "Al Qassim",
      addressCountry: "SA",
    },
    areaServed: {
      "@type": "Country",
      name: "Saudi Arabia",
    },
  };

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${cormorant.variable} ${inter.variable} ${notoKufi.variable} ${plexArabic.variable} ${amiri.variable}`}
      >
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <NextIntlClientProvider messages={messages}>
          <Header />
          <main className="pt-14">{children}</main>
          <Footer />
        </NextIntlClientProvider>
        <Analytics />
      </body>
    </html>
  );
}
