import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { hasLocale } from "next-intl";
import { Cormorant_Garamond, Inter, Noto_Kufi_Arabic } from "next/font/google";
import { routing } from "@/i18n/routing";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import "../globals.css";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-heading",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const notoKufi = Noto_Kufi_Arabic({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-arabic",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    // Child pages supply just their page name; this template appends the site name.
    template: "%s — DarSaif",
    default: "DarSaif Architecture",
  },
  description: "Architecture office based in Buraydah, Qassim, Saudi Arabia.",
  openGraph: {
    siteName: "DarSaif Architecture",
    type: "website",
    // Default og:image is generated by opengraph-image.tsx (next/og convention).
    // Per-project pages override this with their Sanity cover image.
  },
  twitter: {
    card: "summary_large_image",
  },
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  const siteUrl =
    process.env.NEXT_PUBLIC_SITE_URL ?? "https://darsaif.com";

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    name: "DarSaif Architecture",
    description:
      "Architecture office based in Buraydah, Qassim, Saudi Arabia.",
    url: siteUrl,
    address: {
      "@type": "PostalAddress",
      addressLocality: "Buraydah",
      addressRegion: "Al Qassim",
      addressCountry: "SA",
    },
    areaServed: {
      "@type": "Country",
      name: "Saudi Arabia",
    },
  };

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${cormorant.variable} ${inter.variable} ${notoKufi.variable}`}
      >
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <NextIntlClientProvider messages={messages}>
          <Header />
          <main className="pt-16">{children}</main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
